### ISSUE TITLE
Unhnandled Promise Rejection

### ISSUE THREAD

**Issue by rxmarbles** [godaddy/orglinter#16]
When using the package I uncovered this error
```
 ~/dev/work/ghe/oswg/github_membership   master ±  npx orglinter godaddy.toml
npx: installed 16 in 4.035s
Loaded config for godaddy. 141 memberships expected.
Retrieving 100 GitHub members...
Retrieving 100 GitHub members...
140 total members retrieved.
0 two factor auth violators found:  []
0 undocumented memberships found:  []
1 new memberships requested:  [ 'rmarkins-godaddy' ]
Setting rmarkins-godaddy up as a(n) admin for godaddy.
0 demotions found:  []
(node:46771) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'role' of undefined
    at /Users/rmarkins/.npm/_npx/46771/lib/node_modules/orglinter/src/lib/checkers.js:25:69
    at Array.filter (<anonymous>)
    at Object.findPromotions (/Users/rmarkins/.npm/_npx/46771/lib/node_modules/orglinter/src/lib/checkers.js:24:46)
    at /Users/rmarkins/.npm/_npx/46771/lib/node_modules/orglinter/bin/cli.js:61:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:46771) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46771) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
rmarkins-godaddy successfully invited to godaddy!
```

It appears that when sending a new request it has an issue w/ role

**Comment by tarkatronic** [comment]
Hmmmm, it looks like a problem with this filter: https://github.com/godaddy/orglinter/blob/1b75cd7071eaf0efaf459992fb40f29d3d264424/src/lib/checkers.js#L24-L26

I think this may need to be changed to something more like

```js
  (member) => configured[members] === 'ADMIN' && retrieved[member] && retrieved[member].role === 'MEMBER'
```

Adding that additional existence check there in the middle. I swear it did this in the past, but it must have gotten removed at some point. Or would that be better done with `.hasOwnProperty(member)`?

It looks like it's erroring out on the fact that your `rmarkins-godaddy` doesn't yet exist in the org, so it doesn't exist in the `retrieved` object.
